### ISSUE TITLE
lintOnFlyInterval specified

### ISSUE THREAD

**Issue by Arcanemagus** [stadt-bielefeld/atom-mapfile#2]
While researching something else I came across this package specifying `lintOnFlyInterval` in the properties for it's Linter provider. That isn't something that is able to be specified there, you can see the only supported properties for a v1 provider [here](https://github.com/steelbrain/linter/blob/v1/docs/types/standard-linter-v1.md). That property is just being ignored, so it's not a high priority fix, but I figured I should let you know 😉.

Also note that Linter v2 is out, you can find a guide to help migrate your provider over to it [here](https://github.com/steelbrain/linter/blob/master/docs/guides/upgrading-to-standard-linter-v2.md).

**Comment by geofreak** [comment]
I fixed that. :-)
